name: Keep Render Awake

on:
  schedule:
    - cron: "*/5 * * * *"  # jalan tiap 5 menit
  workflow_dispatch:       # bisa dijalankan manual juga

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping root domain
        run: |
          curl -s --max-time 10 https://pasmeal.onrender.com/ > /dev/null
